;=================================================
; This setting.ini for caputure.au3(exe) 
; Read only 
; 行先頭以外のセミコロンコメントは認められていないので注意
;=================================================
;Capture key
D_CAPTURE_KEY="9"

;ページめくりクリック座標　横画面・（左・ゴラクエッグに対応した座標）★★　座標を再調査
D_L_CLICK_X=20
D_L_CLICK_Y=1260

; 画面サイズの設定
D_HEIGHT=1440
D_WIDTH=2528

;　領域指定では無く、中心座標に対してエリアサイズ（/2) を指定
D_CHECK_HALF_SIZE=250

;■Wait Timer Counter
D_WAITTIMER_NORMAL=0
D_WAITTIMER_LONG=3000

;=================================================
;となりのヤンジャン連続
;■終端後次話ボタン座標　★★
DYJ_NEXT_X=654
DYJ_NEXT_Y=1311

;■全画面ボタン座標　★★
DYJ_FULLSCR_X=794
DYJ_FULLSCR_Y=2494

;■LOADING背景色検出(となりのヤンジャン)　サム値ではない　確定値
D_YOUNGJUMP_BACKCOLOR=15724527

;=================================================
;■Komiflo 終端座標(X座標)と 対応色 COL2はいまのところ予備
DKM_END_PIXEL_X=132
DKM_END_PIXEL_Y=254
DKM_END_COL1=2236962
DKM_END_COL2=2236962

;=================================================
;■Ebook連続　次巻クリック座標,色
D_EB_BACKCOLOR=16119285

DEB_NEXT_X=1295
DEB_NEXT_Y=130

DEB_NEXT_COLOR=15288160
;DEB_NEXT_COLOR=16271454

;■LOADING背景色検出(EBOOKJAPAN) サム値ではない　確定値（グレー・背景）
D_EBJ_BACKCOLOR=11776947

;=================================================
;■DAYS フルスクリーン復帰
DCD_FSCREEN_X=1341
DCD_FSCREEN_Y=1407

;■DAYS 終端色
DCD_ENDCOLORA=12855078
DCD_ENDCOLORB=13844285
;■DAYS 全画面雑誌終端X座標（左右）
DCD_ENDAXPOSL=717
;(Rみかくにん)
DCD_ENDAXPOSR=1787
DCD_ENDAYPOS=714
;■DAYS 単話終端X座標（上下左右）
DCD_ENDBXPOSL=892
DCD_ENDBXPOSR=1666
DCD_ENDBYPOS=600

;■LOADING背景色検出(COMICDAYS)　サム値ではない　確定値
D_CDAYS_BACKCOLOR=3355443
;=================================================

;■ヤンマガWEB　中央　次話ボタン
DYM_ENDXPOS=1297
DYM_ENDYPOS=708
DYM_ENDCOLOR=0

;=================================================
;■BOOKWALER 次ボタン, 色　
; Y-430to850
DBW_NEXT_POS_X=1333
DBW_NEXT_COL2=2308431
DBW_NEXT_COL1=1978691

;MISHIYOU
DBW_NEXT_POS_Y=678

;■LOADING背景色検出(BOOKWALKER) サム値ではない　確定値（グレー・背景）
D_BW_BACKCOLOR1=3881787
D_BW_BACKCOLOR2=3881787

;=================================================

;JUMP+ インデックス表示／インデックス戻り／インデックス先頭
D_JP_INDEX_X=1300
D_JP_INDEX_Y=1300
D_JP_RESET_X=2522
D_JP_RESET_Y=1291
D_JP_TOPINDEX_X=2400
D_JP_TOPINDEX_Y=1300

;■LOADING背景色検出(ジャンプ＋)　サム値ではない　確定値
D_JUMPPLUS_BACKCOLOR=10461087

;=================================================

;■LOADING背景色検出(ヤンジャン定期)　サム値ではない　確定値
D_YOUNGJUMP_TEIKI_BACKCOLOR=15724527

;=================================================
;NOX+サンデーうぇぶり　単行本連続　ページめくり・次本位置
D_NOX_SW_PAGE_X=189
D_NOX_SW_PAGE_Y=628

D_NOX_SW_NEXT_X=1137
D_NOX_SW_NEXT_Y=1019


;=================================================
;FUZ 次号位置
DFZ_NEXT_POS_X1=750
DFZ_NEXT_POS_X2=1385
DFZ_NEXT_POS_Y=525

DFZ_COLOR=6468585


