; キャプチャに使用するキー
; キャプチャに使用するキー
; キャプチャに使用するキー
; キャプチャに使用するキー
; キャプチャに使用するキー
; キャプチャに使用するキー
D_CAPTURE_KEY="9"

; ページ送りクリック位置
D_L_CLICK_X=20
D_L_CLICK_Y=1260

; 画面サイズ
D_HEIGHT=1440
D_WIDTH=2528

; 画面判定範囲の半径
D_CHECK_HALF_SIZE=250

; 通常・長時間待機時間
D_WAITTIMER_NORMAL=0
D_WAITTIMER_LONG=3000

; となりのヤングジャンプのページ送り位置
; となりのヤングジャンプのページ送り位置
; となりのヤングジャンプのページ送り位置
DYJ_NEXT_X=654
DYJ_NEXT_Y=1311

; となりのヤングジャンプの全画面ボタン位置
DYJ_FULLSCR_X=794
DYJ_FULLSCR_Y=2494

; ヤングジャンプのローディング色
D_YOUNGJUMP_BACKCOLOR=15724527

; Komiflo の終了判定設定
; Komiflo の終了判定設定
DKM_END_PIXEL_X=132
DKM_END_PIXEL_Y=254
DKM_END_COL1=2236962
DKM_END_COL2=2236962

; ebookJapan のローディング色
; ebookJapan のローディング色
D_EB_BACKCOLOR=16119285

DEB_NEXT_X=1295
DEB_NEXT_Y=130

DEB_NEXT_COLOR=15288160
; 設定項目

; 設定項目
D_EBJ_BACKCOLOR=11776947

; DAYS のページ送り・終了判定設定
; DAYS のページ送り・終了判定設定
DCD_FSCREEN_X=1341
DCD_FSCREEN_Y=1407

; DAYS のページ送り・終了判定設定
DCD_ENDCOLORA=12855078
DCD_ENDCOLORB=13844285
; DAYS のページ送り・終了判定設定
DCD_ENDAXPOSL=717
; DAYS のページ送り・終了判定設定
DCD_ENDAXPOSR=1787
DCD_ENDAYPOS=714
; DAYS のページ送り・終了判定設定
DCD_ENDBXPOSL=892
DCD_ENDBXPOSR=1666
DCD_ENDBYPOS=600

; 設定項目
D_CDAYS_BACKCOLOR=3355443
; ヤングマガジンWEBの終了ボタン設定

; ヤングマガジンWEBの終了ボタン設定
DYM_ENDXPOS=1297
DYM_ENDYPOS=708
DYM_ENDCOLOR=0

; BookWalker のページ送り設定
; BookWalker のページ送り設定
; BookWalker のページ送り設定
DBW_NEXT_POS_X=1333
DBW_NEXT_COL2=2308431
DBW_NEXT_COL1=1978691

; BookWalker のページ送り設定
DBW_NEXT_POS_Y=678

; BookWalker のローディング色
D_BW_BACKCOLOR1=3881787
D_BW_BACKCOLOR2=3881787

; ジャンププラスのインデックス操作設定

; ジャンププラスのインデックス操作設定
D_JP_INDEX_X=1300
D_JP_INDEX_Y=1300
D_JP_RESET_X=2522
D_JP_RESET_Y=1291
D_JP_TOPINDEX_X=2400
D_JP_TOPINDEX_Y=1300

; 設定項目
D_JUMPPLUS_BACKCOLOR=10461087

; ヤングジャンプのローディング色

; ヤングジャンプのローディング色
D_YOUNGJUMP_TEIKI_BACKCOLOR=15724527

; NOX+ のページ切り替え設定
; NOX+ のページ切り替え設定
D_NOX_SW_PAGE_X=189
D_NOX_SW_PAGE_Y=628

D_NOX_SW_NEXT_X=1137
D_NOX_SW_NEXT_Y=1019


; FUZ のページ送り設定
; FUZ のページ送り設定
DFZ_NEXT_POS_X1=750
DFZ_NEXT_POS_X2=1385
DFZ_NEXT_POS_Y=525

DFZ_COLOR=6468585


